Actually make the check fail.

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -20,4 +20,4 @@ jobs:
           files-changed-only: false  # same as above
       - name: Check results
         if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!"
+        run: echo "Some files failed the linting checks!" && exit 1
